import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { XMLParser } from 'fast-xml-parser';

const root = resolve(import.meta.dirname, '../..');
const args = new Set(process.argv.slice(2));
const debug = args.has('--debug-layout');
const inputDir = resolve(root, args.has('--input') ? process.argv[process.argv.indexOf('--input') + 1] : 'temp/pdf2md');
const outputFile = resolve(root, args.has('--output') ? process.argv[process.argv.indexOf('--output') + 1] : 'src/content/docs/modernising-with-free-software/index.md');
const assetDir = resolve(root, 'src/content/docs/modernising-with-free-software/assets');
const metadataFile = resolve(root, 'src/content/docs/modernising-with-free-software/source-metadata.json');
const layout = JSON.parse(await readFile(resolve(import.meta.dirname, 'layout.json'), 'utf8'));
const fixups = JSON.parse(await readFile(resolve(import.meta.dirname, 'fixups.json'), 'utf8'));

const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_', trimValues: false });
const xml = await readFile(resolve(inputDir, 'layout.html'), 'utf8');
const parsed = parser.parse(xml);
const pages = asArray(parsed.html?.body?.doc?.page);

if (pages.length !== 32) throw new Error(`Expected 32 PDF pages, found ${pages.length}.`);

const sourceHash = createHash('sha256').update(await readFile(resolve(root, layout.source))).digest('hex');
const metadata = {
  source: layout.source,
  sourceHash,
  poppler: (await readFile(resolve(inputDir, 'poppler-version.txt'), 'utf8')).trim(),
  pdfinfo: (await readFile(resolve(inputDir, 'pdfinfo.txt'), 'utf8')).trim(),
  fonts: (await readFile(resolve(inputDir, 'fonts.txt'), 'utf8')).trim(),
};

const output = [
  '---',
  'title: Modernising Public Infrastructure with Free Software',
  'description: Public Money Public Code — modernising public infrastructure with Free Software.',
  '---',
  '',
  '<!-- Generated by tools/pdf2md/convert.mjs. Do not edit by hand. -->',
  `<!-- Source: ${metadata.source}; SHA-256: ${metadata.sourceHash}; ${metadata.poppler} -->`,
  '',
];
const debugPages = [];

for (const [index, page] of pages.entries()) {
  const pageNumber = index + 1;
  const regions = layout.pages[String(pageNumber)] ?? layout.pages.default;
  const images = layout.images?.[String(pageNumber)] ?? [];
  const blocks = collectBlocks(page);
  const assigned = blocks.map((block) => ({ block, region: findRegion(block, regions) }));
  const uncovered = assigned.filter(({ block, region }) => !region && !isPageNumber(block.text));
  if (uncovered.length) throw new Error(`Unassigned text on PDF page ${pageNumber}: ${uncovered.map(({ block }) => block.text).join(' | ')}`);
  debugPages.push({ page: pageNumber, blocks: assigned.map(({ block, region }) => ({ ...block, region: region?.id ?? null })) });

  // Omitted pages produce no page marker, text, or image output at all.
  if (regions.some((region) => region.omit)) continue;

  output.push(`<!-- Source PDF page ${pageNumber} -->`);

  const text = applyFixups(joinBlocks(assigned
    .filter(({ region }) => region)
    .sort(({ block: a, region: regionA }, { block: b, region: regionB }) => regionA.order - regionB.order || a.yMin - b.yMin || a.xMin - b.xMin)
    .map(({ block }) => block.text)
    .filter((text) => !isPageNumber(text))));

  const content = placeImages(text, images, pageNumber);
  if (content) output.push(content, '');
}

await mkdir(dirname(outputFile), { recursive: true });
await writeFile(outputFile, `${output.join('\n').trimEnd()}\n`);
await mkdir(assetDir, { recursive: true });
for (const image of Object.values(layout.images ?? {}).flat()) await copyFile(resolve(inputDir, image.source), resolve(assetDir, image.source));
await writeFile(metadataFile, `${JSON.stringify(metadata, null, 2)}\n`);
if (debug) await writeFile(resolve(inputDir, 'layout-debug.json'), `${JSON.stringify({ metadata, pages: debugPages }, null, 2)}\n`);
console.log(`Wrote ${relative(root, outputFile)} from ${pages.length} PDF pages.`);

function asArray(value) { return value === undefined ? [] : Array.isArray(value) ? value : [value]; }
function collectBlocks(page) {
  return asArray(page.flow).flatMap((flow) => asArray(flow.block)).flatMap((block) => {
    const lines = asArray(block.line).map(lineText).filter(Boolean);
    const text = joinLines(lines);
    return text ? [{ text, xMin: Number(block['@_xMin']), yMin: Number(block['@_yMin']), xMax: Number(block['@_xMax']), yMax: Number(block['@_yMax']) }] : [];
  });
}
function joinLines(lines) { return lines.reduce((text, line) => !text ? line : /[\-‐]$/.test(text) && /^[a-z]/.test(line) ? `${text.slice(0, -1)}${line}` : `${text} ${line}`, ''); }
function joinBlocks(blocks) {
  return blocks.reduce((text, block) => {
    if (!text) return block;
    if (/[\-‐]$/.test(text) && /^[a-z]/.test(block)) return `${text.slice(0, -1)}${block}`;
    if (!/[.!?:;”"]$/.test(text) && /^[a-z]/.test(block)) return `${text} ${block}`;
    return `${text}\n\n${block}`;
  }, '');
}
function lineText(line) {
  let previous;
  return asArray(line.word).reduce((text, word) => {
    const value = typeof word === 'string' ? word : word['#text'] ?? '';
    const xMin = Number(word['@_xMin']);
    const xMax = Number(word['@_xMax']);
    const joinsPrevious = value === '‐' && previous !== undefined && xMin - previous < 0.2;
    previous = xMax;
    return `${text}${text && !joinsPrevious ? ' ' : ''}${value}`;
  }, '').replace(/\s+/g, ' ').trim();
}
function findRegion(block, regions) { const x = (block.xMin + block.xMax) / 2; const y = (block.yMin + block.yMax) / 2; return regions.find((region) => x >= region.xMin && x <= region.xMax && y >= region.yMin && y <= region.yMax); }
function isPageNumber(text) { return /^\d{1,2}$/.test(text.trim()); }
function applyFixups(text) {
  const cleaned = text.replace(/^·{10,}\s*/gm, '');
  return fixups.replacements.reduce((value, { from, to }) => value.replaceAll(from, to), cleaned);
}
function placeImages(text, images, pageNumber) {
  let result = text;

  for (const image of images) {
    const markdown = `![${image.alt}](./assets/${image.source})`;
    const position = image.position ?? 'start';

    if (position === 'start') {
      result = result ? `${markdown}\n\n${result}` : markdown;
      continue;
    }
    if (position === 'end') {
      result = result ? `${result}\n\n${markdown}` : markdown;
      continue;
    }
    if (position !== 'before' && position !== 'after') {
      throw new Error(`Invalid image position "${position}" for ${image.source} on PDF page ${pageNumber}.`);
    }
    if (!image.anchor) {
      throw new Error(`Image ${image.source} on PDF page ${pageNumber} requires an anchor for position "${position}".`);
    }

    const first = result.indexOf(image.anchor);
    const second = first === -1 ? -1 : result.indexOf(image.anchor, first + image.anchor.length);
    if (first === -1) {
      throw new Error(`Image anchor not found for ${image.source} on PDF page ${pageNumber}: ${JSON.stringify(image.anchor)}`);
    }
    if (second !== -1) {
      throw new Error(`Image anchor is not unique for ${image.source} on PDF page ${pageNumber}: ${JSON.stringify(image.anchor)}`);
    }

    const insertion = position === 'before'
      ? `${markdown}\n\n${image.anchor}`
      : `${image.anchor}\n\n${markdown}`;
    result = `${result.slice(0, first)}${insertion}${result.slice(first + image.anchor.length)}`;
  }

  return result;
}
