import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { XMLParser } from 'fast-xml-parser';

const root = resolve(import.meta.dirname, '../..');
const args = new Set(process.argv.slice(2));
const debug = args.has('--debug-layout');
const inputDir = resolve(root, args.has('--input') ? process.argv[process.argv.indexOf('--input') + 1] : 'temp/pdf2md');
const outputDir = args.has('--output-dir')
  ? resolve(root, process.argv[process.argv.indexOf('--output-dir') + 1])
  : args.has('--output')
    ? dirname(resolve(root, process.argv[process.argv.indexOf('--output') + 1]))
    : resolve(root, 'src/content/docs/modernising-with-free-software');
const assetDir = resolve(outputDir, 'assets');
const metadataFile = resolve(outputDir, 'source-metadata.json');
const layout = JSON.parse(await readFile(resolve(import.meta.dirname, 'layout.json'), 'utf8'));
const fixups = JSON.parse(await readFile(resolve(import.meta.dirname, 'fixups.json'), 'utf8'));

// Article boundaries follow the publication contents. Pages marked `omit` in
// layout.json are still deliberately excluded, including the contents page (5)
// and the infographic spread (16–17).
const sections = [
  { file: '01-editorial.md', startPage: 3, endPage: 3, title: 'Editorial' },
  { file: '02-what-is-free-software.md', startPage: 4, endPage: 4, title: 'What is Free Software?' },
  { file: '03-using-free-software-to-democratise-smart-cities.md', startPage: 6, endPage: 7, title: 'Using Free Software to Democratise Smart Cities' },
  { file: '04-the-costs-of-vendor-lock-in.md', startPage: 8, endPage: 8, title: 'The Costs of Vendor Lock-In' },
  { file: '05-hidden-champions.md', startPage: 9, endPage: 9, title: 'Hidden Champions' },
  { file: '06-the-impact-of-free-software-on-competition.md', startPage: 10, endPage: 11, title: 'The Impact of Free Software on Competition' },
  { file: '07-10-myths-about-free-software.md', startPage: 12, endPage: 13, title: '10 Myths about Free Software' },
  { file: '08-making-business-and-economic-sense-of-free-software.md', startPage: 14, endPage: 15, title: 'Making Business and Economic Sense of Free Software' },
  { file: '10-lessons-from-open-sourcing-in-switzerland.md', startPage: 18, endPage: 19, title: 'Lessons from Open Sourcing in Switzerland' },
  { file: '11-different-options-of-releasing-free-software.md', startPage: 20, endPage: 20, title: 'Different Options of Releasing Free Software' },
  { file: '12-blackbox-election-software.md', startPage: 21, endPage: 21, title: 'Blackbox Election Software' },
  { file: '13-an-open-approach-to-it-security.md', startPage: 22, endPage: 23, title: 'An Open Approach to IT Security' },
  { file: '14-international-cooperation-through-free-software.md', startPage: 24, endPage: 25, title: 'International Cooperation through Free Software' },
  { file: '15-eu-projects-and-policies-supporting-the-use-of-free-software.md', startPage: 26, endPage: 27, title: 'EU Projects and Policies Supporting the Use of Free Software' },
  { file: '16-reprogramming-procurement-law.md', startPage: 28, endPage: 28, title: 'Reprogramming Procurement Law' },
  { file: '17-how-to-procure-free-software.md', startPage: 29, endPage: 29, title: 'How to Procure Free Software' },
  { file: '18-first-steps-to-support-free-software.md', startPage: 30, endPage: 30, title: 'First Steps to Support Free Software' },
];

const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_', trimValues: false });
const xml = await readFile(resolve(inputDir, 'layout.html'), 'utf8');
const parsed = parser.parse(xml);
const pages = asArray(parsed.html?.body?.doc?.page);

if (pages.length !== 32) throw new Error(`Expected 32 PDF pages, found ${pages.length}.`);

const sourceHash = createHash('sha256').update(await readFile(resolve(root, layout.source))).digest('hex');
const metadata = {
  source: layout.source,
  sourceHash,
  poppler: (await readFile(resolve(inputDir, 'poppler-version.txt'), 'utf8')).trim(),
  pdfinfo: (await readFile(resolve(inputDir, 'pdfinfo.txt'), 'utf8')).trim(),
  fonts: (await readFile(resolve(inputDir, 'fonts.txt'), 'utf8')).trim(),
};

const outputs = new Map(sections.map((section) => [section.file, [
  '---',
  `title: ${JSON.stringify(section.title)}`,
  'description: Public Money Public Code — modernising public infrastructure with Free Software.',
  '---',
  '',
  '<!-- Generated by tools/pdf2md/convert.mjs. Do not edit by hand. -->',
  `<!-- Source: ${metadata.source}; SHA-256: ${metadata.sourceHash}; ${metadata.poppler} -->`,
  '',
]]));
const debugPages = [];

for (const [index, page] of pages.entries()) {
  const pageNumber = index + 1;
  const regions = layout.pages[String(pageNumber)] ?? layout.pages.default;
  const images = layout.images?.[String(pageNumber)] ?? [];
  const blocks = collectBlocks(page);
  const assigned = blocks.map((block) => ({ block, region: findRegion(block, regions) }));
  const uncovered = assigned.filter(({ block, region }) => !region && !isPageNumber(block.text));
  if (uncovered.length) throw new Error(`Unassigned text on PDF page ${pageNumber}: ${uncovered.map(({ block }) => block.text).join(' | ')}`);
  debugPages.push({ page: pageNumber, blocks: assigned.map(({ block, region }) => ({ ...block, region: region?.id ?? null })) });

  // Omitted pages produce no page marker, text, image, or section output at all.
  if (regions.some((region) => region.omit)) continue;

  const section = sections.find(({ startPage, endPage }) => pageNumber >= startPage && pageNumber <= endPage);
  if (!section) continue;

  const output = outputs.get(section.file);
  output.push(`<!-- Source PDF page ${pageNumber} -->`);

  const text = applyFixups(joinBlocks(assigned
    .filter(({ region }) => region)
    .sort(({ block: a, region: regionA }, { block: b, region: regionB }) => regionA.order - regionB.order || a.yMin - b.yMin || a.xMin - b.xMin)
    .map(({ block }) => block.text)
    .filter((text) => !isPageNumber(text))));

  const content = placeImages(text, images, pageNumber);
  if (content) output.push(content, '');
}

await mkdir(outputDir, { recursive: true });
await rm(resolve(outputDir, 'index.md'), { force: true });
for (const section of sections) {
  const outputFile = resolve(outputDir, section.file);
  await writeFile(outputFile, `${outputs.get(section.file).join('\n').trimEnd()}\n`);
}
await mkdir(assetDir, { recursive: true });
for (const image of Object.values(layout.images ?? {}).flat()) await copyFile(resolve(inputDir, image.source), resolve(assetDir, image.source));
await writeFile(metadataFile, `${JSON.stringify(metadata, null, 2)}\n`);
if (debug) await writeFile(resolve(inputDir, 'layout-debug.json'), `${JSON.stringify({ metadata, pages: debugPages }, null, 2)}\n`);
console.log(`Wrote ${sections.length} Markdown pages under ${relative(root, outputDir)} from ${pages.length} PDF pages.`);

function asArray(value) { return value === undefined ? [] : Array.isArray(value) ? value : [value]; }
function collectBlocks(page) {
  return asArray(page.flow).flatMap((flow) => asArray(flow.block)).flatMap((block) => {
    const lines = asArray(block.line).map(lineText).filter(Boolean);
    const text = joinLines(lines);
    return text ? [{ text, xMin: Number(block['@_xMin']), yMin: Number(block['@_yMin']), xMax: Number(block['@_xMax']), yMax: Number(block['@_yMax']) }] : [];
  });
}
function joinLines(lines) { return lines.reduce((text, line) => !text ? line : /[\-‐]$/.test(text) && /^[a-z]/.test(line) ? `${text.slice(0, -1)}${line}` : `${text} ${line}`, ''); }
function joinBlocks(blocks) {
  return blocks.reduce((text, block) => {
    if (!text) return block;
    if (/[\-‐]$/.test(text) && /^[a-z]/.test(block)) return `${text.slice(0, -1)}${block}`;
    if (!/[.!?:;”"]$/.test(text) && /^[a-z]/.test(block)) return `${text} ${block}`;
    return `${text}\n\n${block}`;
  }, '');
}
function lineText(line) {
  let previous;
  return asArray(line.word).reduce((text, word) => {
    const value = typeof word === 'string' ? word : word['#text'] ?? '';
    const xMin = Number(word['@_xMin']);
    const xMax = Number(word['@_xMax']);
    const joinsPrevious = value === '‐' && previous !== undefined && xMin - previous < 0.2;
    previous = xMax;
    return `${text}${text && !joinsPrevious ? ' ' : ''}${value}`;
  }, '').replace(/\s+/g, ' ').trim();
}
function findRegion(block, regions) { const x = (block.xMin + block.xMax) / 2; const y = (block.yMin + block.yMax) / 2; return regions.find((region) => x >= region.xMin && x <= region.xMax && y >= region.yMin && y <= region.yMax); }
function isPageNumber(text) { return /^\d{1,2}$/.test(text.trim()); }
function applyFixups(text) {
  const cleaned = text.replace(/^·{10,}\s*/gm, '');
  return fixups.replacements.reduce((value, { from, to }) => value.replaceAll(from, to), cleaned);
}
function placeImages(text, images, pageNumber) {
  let result = text;

  for (const image of images) {
    const markdown = `![${image.alt}](./assets/${image.source})`;
    const position = image.position ?? 'start';

    if (position === 'start') {
      result = result ? `${markdown}\n\n${result}` : markdown;
      continue;
    }
    if (position === 'end') {
      result = result ? `${result}\n\n${markdown}` : markdown;
      continue;
    }
    if (position !== 'before' && position !== 'after') {
      throw new Error(`Invalid image position "${position}" for ${image.source} on PDF page ${pageNumber}.`);
    }
    if (!image.anchor) {
      throw new Error(`Image ${image.source} on PDF page ${pageNumber} requires an anchor for position "${position}".`);
    }

    const first = result.indexOf(image.anchor);
    const second = first === -1 ? -1 : result.indexOf(image.anchor, first + image.anchor.length);
    if (first === -1) {
      throw new Error(`Image anchor not found for ${image.source} on PDF page ${pageNumber}: ${JSON.stringify(image.anchor)}`);
    }
    if (second !== -1) {
      throw new Error(`Image anchor is not unique for ${image.source} on PDF page ${pageNumber}: ${JSON.stringify(image.anchor)}`);
    }

    const insertion = position === 'before'
      ? `${markdown}\n\n${image.anchor}`
      : `${image.anchor}\n\n${markdown}`;
    result = `${result.slice(0, first)}${insertion}${result.slice(first + image.anchor.length)}`;
  }

  return result;
}
